#!/usr/bin/env python3
"""
Script to update cve2_soc.v with firmware from firmware.hex
This is needed because Yosys doesn't synthesize $readmemh for block RAM initialization
"""

import sys
import re

def parse_hex_file(hex_path):
    """Parse firmware.hex and return list of (addr, word) tuples"""
    with open(hex_path, 'r') as f:
        lines = f.readlines()
    
    addr = 0
    words = []
    
    for line in lines:
        line = line.strip()
        if line.startswith('@'):
            addr = int(line[1:], 16)
        elif line:
            bytes_list = line.split()
            i = 0
            while i < len(bytes_list):
                if i + 3 < len(bytes_list):
                    # Little-endian: byte0 is LSB
                    word = bytes_list[i+3] + bytes_list[i+2] + bytes_list[i+1] + bytes_list[i]
                    word_addr = addr // 4
                    words.append((word_addr, word))
                    addr += 4
                    i += 4
                else:
                    break
    
    return words

def generate_init_code(words):
    """Generate Verilog initialization code from word list"""
    lines = []
    lines.append("    // Load firmware - AUTO-GENERATED by update_firmware.py")
    lines.append("    // (Yosys doesn't support $readmemh for block RAM initialization)")
    lines.append("    initial begin")
    for addr, word in words:
        lines.append(f"        memory[{addr}] = 32'h{word};")
    lines.append("    end")
    return '\n'.join(lines)

def update_soc_file(soc_path, init_code):
    """Update cve2_soc.v with new initialization code"""
    with open(soc_path, 'r') as f:
        content = f.read()
    
    # Pattern to match the initialization block
    pattern = r'(    // Load firmware.*?\n    initial begin\n)(.*?)(\n    end)'
    
    # Replace the initialization
    new_content = re.sub(
        pattern,
        r'\1' + '\n'.join([f"        memory[{addr}] = 32'h{word};" 
                           for addr, word in parse_hex_file('firmware/firmware.hex')]) + r'\3',
        content,
        flags=re.DOTALL
    )
    
    # Write back
    with open(soc_path, 'w') as f:
        f.write(new_content)

def main():
    hex_path = 'firmware/firmware.hex'
    soc_path = 'cve2_soc.v'
    
    print(f"Reading firmware from {hex_path}...")
    words = parse_hex_file(hex_path)
    print(f"Found {len(words)} words of firmware")
    
    print(f"Generating initialization code...")
    init_code = generate_init_code(words)
    
    print(f"Updating {soc_path}...")
    update_soc_file(soc_path, init_code)
    
    print("✓ Done! cve2_soc.v updated with new firmware")

if __name__ == '__main__':
    main()
